src/Entity/ToDoList.php
<?php

namespace App\Entity;

use App\Repository\ToDoListRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource
 * @ORM\Entity(repositoryClass="App\Repository\ToDoListRepository")
 */
class ToDoList
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Item", mappedBy="toDoList")
     */
    private $Items;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Item")
     */
    private $lastItem;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", mappedBy="todolist", cascade={"persist", "remove"})
     */
    private $UserP;


    public function canAddItem(Item $item)
    {

//        dump($item->getCreationDate());

        if ($this->lastItem != null){

            $dteDiff  = $this->lastItem->getCreationDate()->diff($item->getCreationDate());
            $secondes =  $dteDiff->days*86400 + $dteDiff->h*3600 + $dteDiff->i*60 + $dteDiff->s;
            if( $secondes > 1800 && count($this->getItems()) < 10){
                return $item;
            }else {
                return null;
            }
        }else {
            return $item;
        }

    }

    public function __construct()
    {
        $this->Items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItems(): Collection
    {
        return $this->Items;
    }

    public function addItem(Item $item): self
    {
        if (!$this->Items->contains($item) && $item != null) {
            $this->Items[] = $item;
            $item->setToDoList($this);
            $this->lastItem = $item;
        }
        return $this;
    }

    public function removeItem(Item $item): self
    {
        if ($this->Items->contains($item)) {
            $this->Items->removeElement($item);
            // set the owning side to null (unless already changed)
            if ($item->getToDoList() === $this) {
                $item->setToDoList(null);
            }
        }
        return $this;
    }

    public function getLastItem(): ?Item
    {
        return $this->lastItem;
    }

    public function setLastItem(?Item $lastItem): self
    {
        $this->lastItem = $lastItem;
        return $this;
    }

    public function getUserP(): ?User
    {
        return $this->UserP;
    }

    public function setUserP(?User $UserP)
    {
        if ($this->UserP) {
            return null;
        }

        $this->UserP = $UserP;

        // set (or unset) the owning side of the relation if necessary
        $newTodolist = null === $UserP ? null : $this;
        if ($UserP->getTodolist() !== $newTodolist) {
            $UserP->setTodolist($newTodolist);
        }

        return $this;
    }
}

templates/list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Todo List{% endblock %}

{% block body %}

<section class="uk-section uk-section-muted uk-flex uk-flex-middle uk-animation-fade background-main3" uk-height-viewport>
	<div class="uk-width-1-1">
		<div class="uk-container">
			<div class="uk-grid-margin uk-grid uk-grid-stack" uk-grid>
				<div class="uk-width-1-1@m">
					<div class="uk-margin uk-width-large uk-margin-auto uk-card uk-card-default uk-card-body uk-box-shadow-large">
                        <h1 class="uk-card-title uk-text-center"><span style='font-size:25px;'>&#128073; </span> Todo List <span style='font-size:25px;'> &#128072;</span></h1>
                            <div class="uk-margin">
								<div class="uk-inline uk-width-1-1">
                                        {% if (list != null) %}
                                            <form method="post" action="{{ path('list_add', {'idList': list.id}) }}">
                                                {{ form_start(form) }}
                                                {{ form_widget(form.name) }}
                                                <br>
                                                <input type="submit" value="Ajouter une tâche" class="uk-button uk-button-primary uk-button-large uk-width-1-1 uk-margin">
                                                {{ form_end(form) }}

                                                <hr class="uk-divider-icon">
                                            </form>

                                            {% for message in app.flashes('success') %}
                                                <p style="color: green;">{{message }}</p>
                                            {%  endfor %}

                                            {% for message in app.flashes('error') %}
                                                <p style="color: red;">{{message }}</p>
                                            {%  endfor %}

                                            {% for item in list.items %}               
                                                <ul class="uk-list uk-list-divider">
                                                    <li>
                                                        <b>Tache :</b> {{ item.name }}
                                                        <br>
                                                        <b>Date :</b> {{ item.creationDate |date("d/m/Y H:i:s")}}
                                                    </li>
                                                </ul>
                                            {% endfor %}
                                        {% else %}
                                            <p>Aucune Liste pour cette utilisateur</p>
                                            <form action="{{ path('list_create', {'idUser': user.id}) }}" method="post">
                                                <input type="submit" value="Créer une nouvelle list" class="uk-button uk-button-primary uk-button-large uk-width-1-1 uk-margin">
                                            </form>
                                        {% endif %}  
								</div>
							</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}